In [2]:
;whoami

desktop-9ulgep1\meric


In [1]:
using Dates
datetimenow = Dates.now()

2023-11-25T16:01:37.205

## 3.2.1 Циклы while и for

In [2]:
n = 0
while n < 10
    n += 1
    print(n, " ")
end

1 2 3 4 5 6 7 8 9 10 

In [3]:
friends = ["Ted", "Robyn", "Yeho", "Heyo", "Teyo"]
i = 1
while i <= length(friends)
    friend = friends[i]
    println("hi $friend, its great to see you!")
    i += 1
end

hi Ted, its great to see you!
hi Robyn, its great to see you!
hi Yeho, its great to see you!
hi Heyo, its great to see you!
hi Teyo, its great to see you!


In [4]:
for n in 1:2:10
    println(n)
end

1
3
5
7
9


In [5]:
friends = ["Ted", "Robyn", "Yeho", "Heyo", "Teyo"]
i = 1
for friend in friends
    println("hi $friend, its great to see you!")
end

hi Ted, its great to see you!
hi Robyn, its great to see you!
hi Yeho, its great to see you!
hi Heyo, its great to see you!
hi Teyo, its great to see you!


In [7]:
m, n = 5, 5
A = fill(0, (m, n))

for i in 1:m
    for j in 1:n
        A[i,j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [8]:
B = fill(0, (m ,n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [9]:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

## 3.2.2. Условные выражения

In [10]:
N = 5

if (N % 3 == 0) && (N % 5 == 0)
    println("Fizzbuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

Buzz


In [11]:
x = 5
y = 10
(x > y) ? x : y

10

## 3.2.3. Функции

In [12]:
function sayhi(name)
    println("hi $name, its great!")
end
sayhi("ok")

hi ok, its great!


In [13]:
function f(x)
    x^2
end
f(4)

16

In [15]:
sayhi2(name) = println("hi $name, its great!")
sayhi2("ok")

hi ok, its great!


In [16]:
f2(x) = x^2
f2(4)

16

In [18]:
sayhi3 = name -> println("hi $name, its great!")
sayhi3("bernard")

hi bernard, its great!


In [19]:
f3 = x -> x^2
f3(41)

1681

In [20]:
v = [3, 5, 2]
sort(v)
v

3-element Vector{Int64}:
 3
 5
 2

In [21]:
sort!(v)
v

3-element Vector{Int64}:
 2
 3
 5

In [22]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [23]:
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

In [24]:
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [25]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [26]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [27]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [28]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [29]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

## 3.2.4. Сторонние библиотеки (пакеты) в Julia

In [31]:
using Colors
palette = distinguishable_colors(100)

In [32]:
rand(palette, 3, 3)

## Задания для самостоятельного выполнения

**1- Используя циклы while и for:**
- выведите на экран целые числа от 1 до 100 и напечатайте их квадраты;

In [36]:
for i in 1:1:100
    print(i)
end

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100

In [37]:
i = 1
while i <= 100
    print(i^2)
    i += 1
end

1491625364964811001211441691962252562893243614004414845295766256767297848419009611024108911561225129613691444152116001681176418491936202521162209230424012500260127042809291630253136324933643481360037213844396940964225435644894624476149005041518453295476562557765929608462416400656167246889705672257396756977447921810082818464864988369025921694099604980110000

- •	создайте словарь squares, который будет содержать целые числа в качестве ключей и квадраты в качестве их пар-значений;

In [38]:
squares = Dict{Int64, Int64}()
for i in 1:1:100
    push!(squares, i => i^2)
end
pairs(squares)

Dict{Int64, Int64} with 100 entries:
  5  => 25
  56 => 3136
  35 => 1225
  55 => 3025
  60 => 3600
  30 => 900
  32 => 1024
  6  => 36
  67 => 4489
  45 => 2025
  73 => 5329
  64 => 4096
  90 => 8100
  4  => 16
  13 => 169
  54 => 2916
  63 => 3969
  86 => 7396
  91 => 8281
  62 => 3844
  58 => 3364
  52 => 2704
  12 => 144
  28 => 784
  75 => 5625
  ⋮  => ⋮

- создайте массив squares_arr, содержащий квадраты всех чисел от 1 до 100.



In [40]:
numbers = []
for i in 1:1:100
    append!(numbers, i)
end

squares_arr = []
i = 1
while i <= length(numbers)
    append!(squares_arr, numbers[i]^2)
    i += 1
end
squares_arr

100-element Vector{Any}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

**2.	Напишите условный оператор, который печатает число, если число чётное, и строку «нечётное», если число нечётное. Перепишите код, используя тернарный оператор.**

In [41]:
N = 5
if N % 2 == 0
    println("чётное")
else 
    println("нечётное")
end

нечётное


In [42]:
N = 4
(N % 2 == 0) ? println("чётное") : println("нечётное")

чётное


**3. Напишите функцию add_one, которая добавляет 1 к своему входу.**

In [43]:
function add_one(X)
    X + 1
end
add_one(5)

6

**4. Используйте  map()  или  broadcast()  для  задания  матрицы  𝐴,   каждый элемент которой увеличивается на единицу по сравнению с предыдущим.**

In [44]:
X = fill(1, 4 * 4)
Y = collect(0:(length(X) - 1))
X = reshape(map(+, X, Y), (4, 4))

4×4 Matrix{Int64}:
 1  5   9  13
 2  6  10  14
 3  7  11  15
 4  8  12  16

**5. Задайте матрицу 𝐴 следующего вида**

In [45]:
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [46]:
# •	Найдите 𝐴 ^ 3.
A^3

3×3 Matrix{Int64}:
 0  0  0
 0  0  0
 0  0  0

In [47]:
# •	Замените третий столбец матрицы 𝐴 на сумму второго и третьего столбцов.
for i in 7:1:9
    A[i] += A[i-3]
end
A

3×3 Matrix{Int64}:
  1   1   4
  5   2   8
 -2  -1  -4

**6- Создайте матрицу 𝐵 с элементами 𝐵𝑖1 = 10, 𝐵𝑖2 = −10, 𝐵𝑖3 = 10, 𝑖 = 1, 2, … , 15.
Вычислите матрицу 𝐶 = 𝐵𝑇𝐵.**

In [49]:
B = Array{Int32, 2}(undef, 15, 3)

for i in 1:1:15
    B[i, 1] = 10
    B[i, 2] = -10
    B[i, 3] = 10
end
B

15×3 Matrix{Int32}:
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10
 10  -10  10

In [50]:
C = (B')*B
C

3×3 Matrix{Int32}:
  1500  -1500   1500
 -1500   1500  -1500
  1500  -1500   1500

**7- Создайте матрицу 𝑍 размерности 6 × 6, все элементы которой равны нулю, и матрицу 𝐸, все элементы которой равны 1. Используя  цикл while или for и закономерности расположения элементов, создайте   следующие матрицы размерности 6 × 6.**

In [54]:
E = ones(Int64, 6, 6)
z1 = zeros(Int64, 6, 6)
for i in 1:1:6
    if i != 1
        z1[i, i - 1] = E[i, i - 1]
    end
    if i != 6
        z1[i, i + 1] = E[i, i + 1]
    end
end
z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [55]:
z2 = zeros(Int64, 6, 6)
for i in 1:1:6
    z2[i,i] = 1 
    if(i+2 <= 6) z2[i, i + 2] = E[i, i + 2] end
    if(i-2 >= 1) z2[i, i - 2] = E[i, i - 2] end
end
z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 1  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [56]:
z3 = zeros(Int64, 6, 6)
for i in 1:1:6
    z3[i,7-i] = 1 
    if(7-i+2 <= 6) z3[i, 9 - i] = E[i, 9 - i] end
    if(7-i-2 >= 1) z3[i, 5 - i] = E[i, 5 - i] end
end
z3

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  0
 1  0  1  0  0  0

In [57]:
z4 = zeros(Int64, 6, 6)
for i in 1:1:6
    z4[i,i] = 1 
    if(i+2 <= 6) z4[i, i + 2] = E[i, i + 2] end
    if(i-2 >= 1) z4[i, i - 2] = E[i, i - 2] end
    if(i+4 <= 6) z4[i, i + 4] = E[i, i + 4] end
    if(i-4 >= 1) z4[i, i - 4] = E[i, i - 4] end
end
z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

**8- В языке R есть функция outer(). Фактически, это матричное умножение с возмож-
ностью изменить применяемую операцию (например, заменить произведение на
сложение или возведение в степень).**

- Напишите свою функцию, аналогичную функции outer() языка R. Функция
должна иметь следующий интерфейс: outer(x,y,operation). Таким образом,
функция вида outer(A,B,*) должна быть эквивалентна произведению матриц
𝐴 и 𝐵 размерностями 𝐿 × 𝑀 и 𝑀 × 𝑁 соответственно, где элементы резуль-
тирующей матрицы 𝐶 имеют вид 𝐶𝑖𝑗 =
𝑀∑𝑘=1𝐴𝑖𝑘𝐵𝑘𝑗 (или в тензорном виде𝐶𝑗𝑖 = 𝑀∑𝑘=1𝐴𝑖𝑘𝐵𝑘𝑗 ).

In [58]:
function outer(x, y, operation)
    if (ndims(x) == 1) x = reshape(x, (size(x, 1), size(x, 2))) end
    if (ndims(y) == 1) y = reshape(y, (size(y, 1), size(y, 2))) end
    c = zeros(size(x)[1], size(y)[2])
    for i in 1:size(x)[1], j in 1:size(y)[2], k in 1:size(x)[2]
        c[i, j] += operation(x[i, k], y[k, j])
    end
    return c
end

outer (generic function with 1 method)

In [65]:
X = [[1 1 3]; [5 2 6]; [-2 -1 -3]]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [66]:
X * X

3×3 Matrix{Int64}:
  0   0   0
  3   3   9
 -1  -1  -3

In [67]:
outer(X, X, *)

3×3 Matrix{Float64}:
  0.0   0.0   0.0
  3.0   3.0   9.0
 -1.0  -1.0  -3.0

- Используя написанную вами функцию outer(), создайте матрицы следующей структуры;

In [72]:
A1 = outer(collect(0:4), collect(0:4)', +)

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  5.0
 2.0  3.0  4.0  5.0  6.0
 3.0  4.0  5.0  6.0  7.0
 4.0  5.0  6.0  7.0  8.0

In [69]:
A2= outer(collect(0:4), collect(1:5)', ^)

5×5 Matrix{Float64}:
 0.0   0.0   0.0    0.0     0.0
 1.0   1.0   1.0    1.0     1.0
 2.0   4.0   8.0   16.0    32.0
 3.0   9.0  27.0   81.0   243.0
 4.0  16.0  64.0  256.0  1024.0

In [71]:
A3 = outer(collect(0:4), collect(0:4)', +).%5

5×5 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0
 1.0  2.0  3.0  4.0  0.0
 2.0  3.0  4.0  0.0  1.0
 3.0  4.0  0.0  1.0  2.0
 4.0  0.0  1.0  2.0  3.0

In [73]:
A4 = outer(collect(0:9), collect(0:9)', +).%10

10×10 Matrix{Float64}:
 0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0
 1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0
 2.0  3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0
 3.0  4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0
 4.0  5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0
 5.0  6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0
 6.0  7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0
 7.0  8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0
 8.0  9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0
 9.0  0.0  1.0  2.0  3.0  4.0  5.0  6.0  7.0  8.0

In [74]:
A5 = outer(collect(0:8), collect(-9:-1)', -).%9

9×9 Matrix{Float64}:
 0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0
 1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0  2.0
 2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0  3.0
 3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0  4.0
 4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0  5.0
 5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0  6.0
 6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0  7.0
 7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0  8.0
 8.0  7.0  6.0  5.0  4.0  3.0  2.0  1.0  0.0

**9- Решите следующую систему линейных уравнений с 5 неизвестными.**

- рассмотрев соответствующее матричное уравнение Ax = 𝑦. Обратите внимание на
особый вид матрицы 𝐴. Метод, используемый для решения данной системы уравне-
ний, должен быть легко обобщаем на случай большего числа уравнений, где матрица
𝐴 будет иметь такую же структуру.

In [75]:
as = Array{Int64, 2}(undef, 5, 5)
m = 5
n = 5

for i in 1:1:m
    for j in 1:1:n
        as[i, j] = 1 + abs(i - j)
    end
end
println(round.(Int32, as))

otvet = [7; -1; -3; 5; 17]

Int32[1 2 3 4 5; 2 1 2 3 4; 3 2 1 2 3; 4 3 2 1 2; 5 4 3 2 1]


5-element Vector{Int64}:
  7
 -1
 -3
  5
 17

In [76]:
as_inv = inv(as)
round.(Int, as_inv)
x_n = round.(Int, as_inv * otvet)

5-element Vector{Int64}:
 -2
  3
  5
  2
 -4

**10- Создайте матрицу 𝑀 размерности 6 × 10, элементами которой являются целые числа, выбранные случайным образом с повторениями из совокупности 1, 2, … , 10.**


In [82]:
M = rand(1:10, 6, 10)

6×10 Matrix{Int64}:
 1   4  5   3  10  5  9   9   2  8
 8  10  8   4   7  1  5  10  10  8
 6   1  7   7   8  5  9   1   7  1
 6   8  7   7   3  6  2   6   8  2
 3   2  4  10   6  8  1   8   9  8
 5   1  7  10   4  7  5   1  10  2

- Найдите число элементов в каждой строке матрицы 𝑀, которые больше числа 𝑁
(например, 𝑁 = 4).

In [80]:
N = 4
for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] > N
            count += 1
        end
    end
    println("Bigger elements: ", N, " in the line: ", i, " equals: ", count)
end

Bigger elements: 4 in the line: 1 equals: 8
Bigger elements: 4 in the line: 2 equals: 6
Bigger elements: 4 in the line: 3 equals: 7
Bigger elements: 4 in the line: 4 equals: 5
Bigger elements: 4 in the line: 5 equals: 6
Bigger elements: 4 in the line: 6 equals: 6


- Определите, в каких строках матрицы 𝑀 число 𝑀 (например, 𝑀 = 7) встречается
ровно 2 раза?

In [84]:
M_ = 7
for i in 1:1:6
    count = 0
    for j in 1:1:10
        if M[i, j] == M_
            count += 1
        end
    end
    if count == 2
        println("the number: ", M_, " Occur at the line: ", i, ", 2 times")
    end
end

the number: 7 Occur at the line: 4, 2 times
the number: 7 Occur at the line: 6, 2 times


- Определите все пары столбцов матрицы 𝑀, сумма элементов которых больше 𝐾
(например, 𝐾 = 75).

In [87]:
function sum75(M, K)
    matrix_new = rand(10)
    for i in 1:1:10
        sum = 0
        for j in 1:1:6
            sum += M[j, i]
        end
        matrix_new[i] = sum
    end
    for i in 1:1:10
        for j in i+1:1:10
            sum = matrix_new[i] + matrix_new[j]
            if sum > K
                println(i, " And ", j)
            end
        end
    end
end
sum75(M, 75)

3 And 4
3 And 5
3 And 9
4 And 5
4 And 8
4 And 9
5 And 9
6 And 9
7 And 9
8 And 9


**11- Вычислите:**

- 20∑𝑖=1 5∑𝑗=1 i^4/(3 + 𝑗),

In [88]:
firstsum = 0
for i in 1:1:20
    for j in 1:1:5
        firstsum += (i^4)/(3+j)
    end
end
println(firstsum)

639215.2833333334


- 20∑𝑖=1 5∑𝑗=1 i^4/(3 + i𝑗),

In [90]:
secondsum = 0
for i in 1:1:20
    for j in 1:1:5
        secondsum += (i^4)/(3+i*j)
    end
end
println(secondsum)

89912.02146097136
