In [4]:
;whoami

desktop-9ulgep1\meric


In [3]:
using Dates
datetimenow = Dates.now()

2023-11-29T19:07:57.283

## 4.2.1. Поэлементные операции над многомерными массивами

In [5]:
a = rand(1:20, (4, 3))

4×3 Matrix{Int64}:
  8  19   9
  6  20  16
  2  20  18
 12  19   9

In [7]:
println("Поэ сумм = ", sum(a))
println("Поэ сумм stol = ", sum(a, dims=1))
println("Поэ сумм strok = ", sum(a, dims=2))

Поэ сумм = 158
Поэ сумм stol = [28 78 52]
Поэ сумм strok = [36; 42; 40; 40;;]


In [8]:
println("Поэ x = ", prod(a))
println("Поэ x stol = ", prod(a, dims=1))
println("Поэ x strok = ", prod(a, dims=2))

Поэ x = 3880584806400
Поэ x stol = [1152 144400 23328]
Поэ x strok = [1368; 1920; 720; 2052;;]


In [9]:
import Pkg
Pkg.add("Statistics")
using Statistics

    Updating registry at `C:\Users\Meric\.julia\registries\General.toml`
   Resolving package versions...
    Updating `C:\Users\Meric\.julia\environments\v1.9\Project.toml`
  [10745b16] + Statistics v1.9.0
  No Changes to `C:\Users\Meric\.julia\environments\v1.9\Manifest.toml`


In [10]:
println("median of the matrix= ", mean(a))
println("median of the matrix row= ", mean(a, dims=1))
println("median of the matrix column= ", mean(a, dims=2))

median of the matrix= 13.166666666666666
median of the matrix row= [7.0 19.5 13.0]
median of the matrix column= [12.0; 14.0; 13.333333333333334; 13.333333333333334;;]


## 4.2.2. Транспонирование, след, ранг, определитель и инверсия матрицы

In [11]:
import Pkg
Pkg.add("LinearAlgebra")
using LinearAlgebra

   Resolving package versions...
    Updating `C:\Users\Meric\.julia\environments\v1.9\Project.toml`
  [37e2e46d] + LinearAlgebra
  No Changes to `C:\Users\Meric\.julia\environments\v1.9\Manifest.toml`


In [12]:
b = rand(1:20, (4,4))

4×4 Matrix{Int64}:
  4  10   9   9
 12  10  16   7
 13  19  12   3
  4   7  20  18

In [16]:
println(transpose(b))
println(tr(b))
println(diag(b))
println(rank(b))
println(inv(b))
println(det(b))
println(pinv(b))

[4 12 13 4; 10 10 19 7; 9 16 12 20; 9 7 3 18]
44
[4, 10, 12, 18]
4
[0.4333045231921632 0.38461538461538436 -0.31489484298473036 -0.3137424373379427; -0.05646787669259574 -0.1538461538461538 0.13944108326130794 0.06482281763180636; -0.5004321521175449 -0.2307692307692305 0.2765773552290403 0.2938634399308554; 0.48170556035724527 0.2307692307692305 -0.29155862863728 -0.22644770959377675]
-3471.0000000000045
[0.43330452319216395 0.3846153846153846 -0.3148948429847305 -0.3137424373379431; -0.05646787669259577 -0.15384615384615377 0.1394410832613079 0.06482281763180636; -0.5004321521175458 -0.23076923076923087 0.27657735522904064 0.29386343993085584; 0.4817055603572461 0.23076923076923087 -0.2915586286372804 -0.22644770959377716]


## 4.2.3. Вычисление нормы векторов и матриц, повороты, вращения

In [17]:
X = [2, 4, -5]

3-element Vector{Int64}:
  2
  4
 -5

In [18]:
norm(X)

6.708203932499369

In [21]:
p = 1
norm(X, p)

11.0

In [22]:
Y = [1, -1, 3]
norm(X-Y)

9.486832980505138

In [24]:
sqrt(sum((X-Y).^2))

9.486832980505138

In [26]:
acos((transpose(X)*Y)/(norm(X)*norm(Y)))

2.4404307889469252

In [27]:
d = [5 -4 2; -1 2 3; -2 1 0]
println(opnorm(d))
p = 1
println(opnorm(d, p))

7.147682841795258
8.0


In [28]:
println(rot180(d))
println(reverse(d, dims=1))
println(reverse(d, dims=2))

[0 1 -2; 3 2 -1; 2 -4 5]
[-2 1 0; -1 2 3; 5 -4 2]
[2 -4 5; 3 2 -1; 0 1 -2]


## 4.2.4. Матричное умножение, единичная матрица, скалярное произведение

In [31]:
A = rand(1:10, (2, 3))

2×3 Matrix{Int64}:
 1  9  9
 8  4  9

In [32]:
B = rand(1:10, (3, 4))

3×4 Matrix{Int64}:
 9  1  3   4
 6  5  7  10
 3  4  9  10

In [33]:
A*B

2×4 Matrix{Int64}:
  90  82  147  184
 123  64  133  162

In [34]:
Matrix{Int}(I, 3, 3)

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

In [35]:
X = [2, 4, -5]
Y = [1, -1, 3]
dot(X,Y)

-17

In [37]:
X'Y

-17

## 4.2.5. Факторизация. Специальные матричные структуры

In [38]:
# Задаём квадратную матрицу 3x3 со случайными значениями:
A = rand(3, 3)
# Задаём единичный вектор:
x = fill(1.0, 3)
# Задаём вектор b:
b = A*x
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
A\b

3-element Vector{Float64}:
 1.0000000000000002
 0.9999999999999994
 0.9999999999999998

In [40]:
Alu = lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.981188  1.0       0.0
 0.093869  0.571523  1.0
U factor:
3×3 Matrix{Float64}:
 0.989966  0.361416   0.957735
 0.0       0.317975  -0.875719
 0.0       0.0        1.30668

In [41]:
# Матрица перестановок:
println(Alu.P)
# Вектор перестановок:
println(Alu.p)
# Матрица L:
println(Alu.L)
# Матрица U:
println(Alu.U)

[0.0 1.0 0.0; 1.0 0.0 0.0; 0.0 0.0 1.0]
[2, 1, 3]
[1.0 0.0 0.0; 0.9811875060245201 1.0 0.0; 0.09386904025287925 0.5715226931678186 1.0]
[0.9899656586718115 0.36141582652610316 0.9577351892863605; 0.0 0.31797469080805146 -0.8757190546732735; 0.0 0.0 1.3066806028419102]


In [43]:
# Решение СЛАУ через матрицу A:
println(A\b)
# Решение СЛАУ через объект факторизации:
println(Alu\b)
# Детерминант матрицы A:
println(det(A))
# Детерминант матрицы A через объект факторизации:
println(det(Alu))

[1.0000000000000002, 0.9999999999999994, 0.9999999999999998]
[1.0000000000000002, 0.9999999999999994, 0.9999999999999998]
-0.41132217854162295
-0.41132217854162295


In [44]:
# QR-факторизация:
Aqr = qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor:
3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}:
 -0.698794    0.547924  -0.459855
 -0.712192   -0.593001   0.375675
 -0.0668528   0.590024   0.804613
R factor:
3×3 Matrix{Float64}:
 -1.39003  -0.741818  -0.786719
  0.0       0.281451  -0.00415733
  0.0       0.0        1.05137

In [45]:
# Матрица Q:
Aqr.Q
# Матрица R:
Aqr.R

3×3 Matrix{Float64}:
 -1.39003  -0.741818  -0.786719
  0.0       0.281451  -0.00415733
  0.0       0.0        1.05137

In [46]:
# Проверка, что матрица Q - ортогональная:
Aqr.Q'*Aqr.Q

3×3 Matrix{Float64}:
 1.0  2.22045e-16  -5.55112e-17
 0.0  1.0           5.55112e-17
 0.0  1.11022e-16   1.0

In [47]:
# Симметризация матрицы A:
Asym = A + A'
# Спектральное разложение симметризованной матрицы:
AsymEig = eigen(Asym)
# Собственные значения:
println(AsymEig.values)
#Собственные векторы:
println(AsymEig.vectors)

[-0.7573078033156504, 1.6942896755170211, 3.5207115987978415]
[0.47804116299291866 -0.5733501442154171 -0.6653918083449313; -0.8086923256831721 0.008332038195838706 -0.5881728483368179; 0.3427730573798355 0.8192680814407841 -0.4596808043271076]


In [48]:
# Проверяем, что получится единичная матрица:
inv(AsymEig)*Asym

3×3 Matrix{Float64}:
  1.0          -2.22045e-16   2.33147e-15
 -2.91434e-16   1.0          -2.44249e-15
  4.64906e-16   4.44089e-16   1.0

In [49]:
# Матрица 1000 х 1000:
n = 1000
A = randn(n,n)
# Симметризация матрицы:
Asym = A + A'
# Проверка, является ли матрица симметричной:
issymmetric(Asym)

true

In [50]:
# Добавление шума:
Asym_noisy = copy(Asym)
Asym_noisy[1,2] += 5eps()
# Проверка, является ли матрица симметричной:
issymmetric(Asym_noisy)

false

In [51]:
# Явно указываем, что матрица является симметричной:
Asym_explicit = Symmetric(Asym_noisy)

1000×1000 Symmetric{Float64, Matrix{Float64}}:
  2.33259     1.24608   -0.832214   …   2.19706    -0.126905   -2.48381
  1.24608     0.497223   1.22765       -1.45947    -0.209887   -2.44809
 -0.832214    1.22765   -0.202109       2.08392     0.238723   -0.304849
  1.07963     0.194836  -1.22967        3.51239    -2.61566     1.33111
 -1.88183    -0.208622   0.796256       1.39145    -1.82287    -0.811982
 -1.62107    -0.864373  -0.0431974  …   0.215726   -1.99076     0.0682212
  0.0156327  -1.1294     1.4299         0.280924   -1.16165     1.42649
 -3.62033    -2.77724    2.01887       -0.419585    3.40777     1.14429
  0.140673    0.584869  -2.88876        2.03199     2.01124    -0.956388
  0.229501   -1.12723   -0.356529       0.357365    0.859083   -2.06559
 -0.964592   -0.866007  -2.54939    …   1.49075     1.54792    -1.11999
 -2.68168    -1.2316    -0.0251803     -0.605191    1.12469     0.951216
 -2.60726    -0.237948   0.13153       -2.56382    -0.571761    1.43782
  ⋮        

In [52]:
import Pkg
Pkg.add("BenchmarkTools")
using BenchmarkTools
# Оценка эффективности выполнения операции по нахождению
# собственных значений симметризованной матрицы:
@btime eigvals(Asym);

   Resolving package versions...
   Installed BenchmarkTools ─ v1.3.2
    Updating `C:\Users\Meric\.julia\environments\v1.9\Project.toml`
  [6e4b80f9] + BenchmarkTools v1.3.2
    Updating `C:\Users\Meric\.julia\environments\v1.9\Manifest.toml`
  [6e4b80f9] + BenchmarkTools v1.3.2
  [9abbd945] + Profile
Precompiling project...
  ✓ BenchmarkTools
  1 dependency successfully precompiled in 3 seconds. 37 already precompiled.

  616.109 ms (11 allocations: 7.99 MiB)


In [53]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы:
@btime eigvals(Asym_noisy);

  1.381 s (14 allocations: 7.93 MiB)


In [54]:
# Оценка эффективности выполнения операции по нахождению
# собственных значений зашумлённой матрицы,
# для которой явно указано, что она симметричная:
@btime eigvals(Asym_explicit);

  379.913 ms (11 allocations: 7.99 MiB)


In [55]:
# Трёхдиагональная матрица 1000000 х 1000000:
n = 1000000;
A = SymTridiagonal(randn(n), randn(n-1))
# Оценка эффективности выполнения операции по нахождению
# собственных значений:
@btime eigmax(A)

  996.960 ms (17 allocations: 183.11 MiB)


6.128380710256792

## 4.2.6. Общая линейная алгебра

In [56]:
# Матрица с рациональными элементами:
Arational = Matrix{Rational{BigInt}}(rand(1:10, 3, 3))/10
# Единичный вектор:
x = fill(1, 3)
# Задаём вектор b:
b = Arational*x
# Решение исходного уравнения получаем с помощью функции \
# (убеждаемся, что x - единичный вектор):
Arational\b
# LU-разложение:
lu(Arational)

LU{Rational{BigInt}, Matrix{Rational{BigInt}}, Vector{Int64}}
L factor:
3×3 Matrix{Rational{BigInt}}:
 1//1  0//1   0//1
 1//5  1//1   0//1
 4//5  4//31  1//1
U factor:
3×3 Matrix{Rational{BigInt}}:
 1//1   9//10   2//5
 0//1  31//50  41//50
 0//1   0//1   23//310

## 4.3. Задание
1. Используя Jupyter Lab, повторите примеры из раздела 4.2.
2. Выполните задания для самостоятельной работы (раздел 4.4).
### 4.4. Задания для самостоятельного выполнения

**4.4.1. Произведение векторов**
1. Задайте вектор v. Умножьте вектор v скалярно сам на себя и сохраните результат
в dot_v.
2. Умножьте v матрично на себя (внешнее произведение), присвоив результат перемен-
ной outer_v.

In [57]:
v = [4, 2, -10, 3]
dot_v = dot(v, v)

129

In [58]:
outer_v = v * v'

4×4 Matrix{Int64}:
  16    8  -40   12
   8    4  -20    6
 -40  -20  100  -30
  12    6  -30    9

**4.4.2. Системы линейных уравнений**
1. Решить СЛАУ с двумя неизвестными.

In [66]:
A_1 = [1 1; 1 -1]
B_1 = [2; 3]
try
    A_1\B_1
catch err
    print(err)
end

2-element Vector{Float64}:
  2.5
 -0.5

In [65]:
A_2 = [1 1; 2 2]
B_2 = [2; 4]
try
    A_2\B_2
catch err
    print(err)
end

SingularException(2)

In [67]:
A_3 = [1 1; 2 2]
B_3 = [2; 5]
try
    A_3\B_3
catch err
    print(err)
end

SingularException(2)

In [68]:
A_4 = [1 1; 2 2; 3 3]
B_4 = [1; 2; 3]
try
    A_4\B_4
catch err
    print(err)
end

2-element Vector{Float64}:
 0.4999999999999999
 0.5

In [69]:
A_5 = [1 1; 2 1; 1 -1]
B_5 = [2; 1; 3]
try
    A_5\B_5
catch err
    print(err)
end

2-element Vector{Float64}:
  1.5000000000000004
 -0.9999999999999997

In [70]:
A_6 = [1 1; 2 1; 3 2]
B_6 = [2; 1; 3]
try
    A_6\B_6
catch err
    print(err)
end

2-element Vector{Float64}:
 -0.9999999999999989
  2.9999999999999982

2. Решить СЛАУ с тремя неизвестными.

In [71]:
A_7 = [1 1 1; 1 -1 -2]
B_7 = [2; 3]
try
    A_7\B_7
catch err
    print(err)
end

3-element Vector{Float64}:
  2.2142857142857144
  0.35714285714285704
 -0.5714285714285712

In [75]:
A_8 = [1 1 1; 2 2 -3; 3 1 1]
B_8 = [2; 4; 1]
try
    A_8\B_8
catch err
    print(err)
end

3-element Vector{Float64}:
 -0.5
  2.5
  0.0

In [76]:
A_9 = [1 1 1; 1 1 2; 2 2 3]
B_9 = [1; 0; 1]
try
    A_9\B_9
catch err
    print(err)
end

SingularException(2)

In [77]:
A_10 = [1 1 1; 1 1 2; 2 2 3]
B_10 = [1; 0; 0]
try
    A_10\B_10
catch err
    print(err)
end

SingularException(2)

**4.4.3. Операции с матрицами**
1. Приведите приведённые ниже матрицы к диагональному виду

In [78]:
function diagonal_matrices(matrix)
    Asym = matrix + matrix'
    AsymEig = eigen(Asym)
    return inv(AsymEig.vectors) * matrix * AsymEig.vectors
end

diagonal_matrices (generic function with 1 method)

In [80]:
matrix_1 = [1 -2; -2 1]
diagonal_matrices(matrix_1)

2×2 Matrix{Float64}:
 -1.0  0.0
  0.0  3.0

In [81]:
matrix_2 = [1 -2; -2 3]
diagonal_matrices(matrix_2)

2×2 Matrix{Float64}:
 -0.236068     3.46945e-16
  4.44089e-16  4.23607

In [82]:
matrix_3 = [1 -2 0; -2 1 2; 0 2 0]
diagonal_matrices(matrix_3)

3×3 Matrix{Float64}:
 -2.14134       3.55271e-15  -1.9984e-15
  3.38618e-15   0.515138      1.11022e-16
 -6.66134e-16  -4.44089e-16   3.6262

2. Вычислите

In [83]:
([1 -2; -2 1])^10

2×2 Matrix{Int64}:
  29525  -29524
 -29524   29525

In [84]:
sqrt([5 -2; -2 5])

2×2 Matrix{Float64}:
  2.1889   -0.45685
 -0.45685   2.1889

In [85]:
([1 -2; -2 1])^(1/3)

2×2 Symmetric{ComplexF64, Matrix{ComplexF64}}:
  0.971125+0.433013im  -0.471125+0.433013im
 -0.471125+0.433013im   0.971125+0.433013im

In [86]:
sqrt([1 2; 2 3])

2×2 Matrix{ComplexF64}:
 0.568864+0.351578im  0.920442-0.217287im
 0.920442-0.217287im   1.48931+0.134291im

3. Найдите собственные значения матрицы 𝐴, если

In [88]:
A = [140 97 74 168 131;
97 106 89 131 36;
74 89 152 144 71;
168 131 144 54 142;
131 36 71 142 36]
eigenvalues = eigvals(A)

5-element Vector{Float64}:
 -128.49322764802145
  -55.887784553056875
   42.7521672793189
   87.16111477514521
  542.4677301466143

In [89]:
@btime eigvals(A)

  2.611 μs (10 allocations: 2.59 KiB)


5-element Vector{Float64}:
 -128.49322764802145
  -55.887784553056875
   42.7521672793189
   87.16111477514521
  542.4677301466143

- Создайте диагональную матрицу из собственных значений матрицы 𝐴. Создайте
нижнедиагональную матрицу из матрица 𝐴. Оцените эффективность выполняемых
операций.

In [90]:
B = zeros(5, 5)
@btime for i in 1:1:5
    B[i, i] = eigenvalues[i]
end
B

  422.500 ns (5 allocations: 80 bytes)


5×5 Matrix{Float64}:
 -128.493    0.0      0.0      0.0       0.0
    0.0    -55.8878   0.0      0.0       0.0
    0.0      0.0     42.7522   0.0       0.0
    0.0      0.0      0.0     87.1611    0.0
    0.0      0.0      0.0      0.0     542.468

In [91]:
Alu = lu(A)
@btime Alu.L

  110.345 ns (1 allocation: 256 bytes)


5×5 Matrix{Float64}:
 1.0        0.0        0.0       0.0       0.0
 0.779762   1.0        0.0       0.0       0.0
 0.440476  -0.47314    1.0       0.0       0.0
 0.833333   0.183929  -0.556312  1.0       0.0
 0.577381  -0.459012  -0.189658  0.897068  1.0

## 4.4.4. Линейные модели экономики
Линейная модель экономики может быть записана как СЛАУ
𝑥 − 𝐴𝑥 = 𝑦,
где элементы матрицы 𝐴 и столбца 𝑦 — неотрицательные числа. По своему смыслу в экономике элементы матрицы 𝐴 и столбцов 𝑥, 𝑦 не могут быть отрицательными числами.

1. Матрица 𝐴 называется продуктивной, если решение 𝑥 системы при любой неотрица-
тельной правой части 𝑦 имеет только неотрицательные элементы 𝑥𝑖. Используя это
определение, проверьте, являются ли матрицы продуктивными.

In [92]:
function pro_mat(matrix, size)
    ans=""
    E = [1 0; 0 1]
    Y = rand(0:1000, size)
    S = E - matrix
    X = S\Y
    for i in 1:1:size
        if X[i] < 0
            ans = "matrix neproduktivno"
            break
        else
            ans = "matrix produktivno"
        end
    end
    return ans
end

pro_mat (generic function with 1 method)

In [93]:
matrix_1 = [1 2; 3 4]
pro_mat(matrix_1, 2)

"matrix neproduktivno"

In [94]:
matrix_2 = ([1 2; 3 4])*(1/2)
pro_mat(matrix_2, 2)

"matrix neproduktivno"

In [95]:
matrix_3 = ([1 2; 3 4])*(1/10)
pro_mat(matrix_3, 2)

"matrix produktivno"

2. Критерий продуктивности: матрица 𝐴 является продуктивной тогда и только тогда,
когда все элементы матрица
(𝐸 − 𝐴)−1
являются неотрицательными числами. Используя этот критерий, проверьте, являются
ли матрицы продуктивными.

In [96]:
function pro_mat_2(matrix, size)
    ans = ""
    E = [1 0; 0 1]
    matrix_n = E - matrix
    inv_matrix_n = inv(matrix_n)
    for i in 1:1:size
        for j in 1:1:size
            if inv_matrix_n[i, j] < 0
                ans = "matrix neproduktivno"
            break
            else
                ans = "matrix produktivno"
            end
        end
    end
    return ans
end

pro_mat_2 (generic function with 1 method)

In [97]:
matrix_1 = [1 2; 3 1]
pro_mat_2(matrix_1, 2)

"matrix neproduktivno"

In [99]:
matrix_2 = ([1 2; 3 1])*(1/2)
pro_mat_2(matrix_2, 2)

"matrix neproduktivno"

In [100]:
matrix_3 = ([1 2; 3 1])*(1/10)
pro_mat_2(matrix_3, 2)

"matrix produktivno"

3. Спектральный критерий продуктивности: матрица 𝐴 является продуктивной тогда
и только тогда, когда все её собственные значения по модулю меньше 1. Используя
этот критерий, проверьте, являются ли матрицы продуктивными.

In [101]:
function pro_mat_3(matrix, size)
    ans = ""
    eigenvalues = eigvals(matrix)
    for i in 1:1:size
        if abs(eigenvalues[i]) > 1
            ans = "matrix neproduktivno"
            break
        else
            ans = "matrix produktivno"
        end
    end
    return ans
end

pro_mat_3 (generic function with 1 method)

In [102]:
matrix_1 = [1 2; 3 1]
pro_mat_3(matrix_1, 2)

"matrix neproduktivno"

In [106]:
matrix_2 = ([1 2; 3 1])*(1/2)
pro_mat_3(matrix_2, 2)

"matrix neproduktivno"

In [107]:
matrix_3 = ([1 2; 3 1])*(1/10)
pro_mat_3(matrix_3, 2)

"matrix produktivno"

In [108]:
matrix_4 = [0.1 0.2 0.3;
0 0.1 0.2;
0 0.1 0.3]
pro_mat_3(matrix_4, 2)

"matrix produktivno"