# Лабораторная работа № 2. Структуры данных

In [6]:
;whoami

desktop-9ulgep1\meric


In [2]:
using Dates
datetimenow = Dates.now()

2023-11-17T18:14:32.754

### 2.2.1 Кортеж (Tuple) — структура данных (контейнер) в виде неизменяемой индексируемой последовательности элементов какого-либо типа (элементы индексируются с единицы).

In [7]:
favoritelang = ("Python", "Javascript", "Typescript")

x1 = (1, 2, 3)

x2 = (1, 2.0, "tmp")

x3 = (a=2, b=1+2)

print(x1, x2, x3, favoritelang)

(1, 2, 3)(1, 2.0, "tmp")(a = 2, b = 3)("Python", "Javascript", "Typescript")

 - Примеры создания кортежей

In [9]:
length(x2)

3

In [10]:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [11]:
c = x1[2] + x1[3]

5

In [12]:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [13]:
in("tmp", x2), 0 in x2

(true, false)

- Примеры операций над кортежами

### 2.2.2 Словарь — неупорядоченный набор связанных между собой по ключу данных. 

In [15]:
phonebook = Dict("Ivanov i.i" => ("867-2818282", "357-22818173"), "Buxgalteriya" => "273-22828181")

Dict{String, Any} with 2 entries:
  "Ivanov i.i"   => ("867-2818282", "357-22818173")
  "Buxgalteriya" => "273-22828181"

In [16]:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Ivanov i.i"
  "Buxgalteriya"

In [17]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  ("867-2818282", "357-22818173")
  "273-22828181"

In [18]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Ivanov i.i"   => ("867-2818282", "357-22818173")
  "Buxgalteriya" => "273-22828181"

In [19]:
haskey(phonebook, "Ivanov i.i")

true

In [21]:
phonebook["Cidorov p.s"] = "555-28283"

"555-28283"

In [22]:
pop!(phonebook, "Ivanov i.i")

("867-2818282", "357-22818173")

 - Примеры инициализации и операций над словарями

In [24]:
a = Dict("foo" => 0.0, "bar" => 42.0)
b = Dict("baz" => 17, "bar" => 13.0)
merge(a, b), merge(b, a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

- Объединение словарей

### 2.2.3 Множество, как структура данных в Julia, соответствует множеству, как математическому объекту, то есть является неупорядоченной совокупностью элементов какого-либо типа. 

- Синтаксис определения множества: **Set([itr])**, где itr — набор значений, сгенерированных данным итерируемым объектом или пустое множество.

In [27]:
A = Set([1, 3, 4, 5])
B = Set("heyeyeyeyee")

Set{Char} with 3 elements:
  'e'
  'h'
  'y'

In [28]:
S1 = Set([1,2])
S2 = Set([3,4])
issetequal(S1,S2)

false

In [29]:
S3 = Set([1,2,3,1,2,3,1,2,3,3,2,1])
S4 = Set([2,3,1])
issetequal(S3,S4)

true

In [30]:
C = union(S1,S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [31]:
D = intersect(S1,S3)

Set{Int64} with 2 elements:
  2
  1

- Примеры множеств и операций над ними (Часть 1)

In [32]:
E = setdiff(S3,S1)

Set{Int64} with 1 element:
  3

In [33]:
issubset(S1,S4)

true

In [34]:
push!(S4, 101)

Set{Int64} with 4 elements:
  2
  3
  1
  101

In [35]:
pop!(S4)

2

- Примеры множеств и операций над ними (Часть 2)

### 2.2.4 Массив — коллекция упорядоченных элементов, размещённая в многомерной сетке. Векторы и матрицы являются частными случаями массивов. Общий синтаксис одномерных массивов: 


In [36]:
empty_array_1 = []

Any[]

In [37]:
empty_array_2 = (Integer)[]

Integer[]

In [39]:
empty_array_2 = (Float64)[]

Float64[]

- Пример объявления массивов (Часть 1)

In [40]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [41]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [42]:
A = [[1,2,3] [4,5,6] [7,8,9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [43]:
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [47]:
c = rand(1,8)

1×8 Matrix{Float64}:
 0.737333  0.885844  0.786158  0.895768  …  0.0612309  0.419588  0.998475

In [48]:
C = rand(2,3)

2×3 Matrix{Float64}:
 0.572828  0.574703  0.522535
 0.108683  0.746987  0.0949106

- Пример объявления массивов (Часть 2)

In [50]:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.766386   0.620515  0.921842
 0.0712491  0.370415  0.461737
 0.220738   0.665038  0.27332
 0.148201   0.728661  0.75453

[:, :, 2] =
 0.356587  0.95417   0.326633
 0.807853  0.996228  0.713011
 0.345924  0.828091  0.0751249
 0.750026  0.998282  0.265504

In [52]:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

- Пример объявления массивов (Часть 3)

In [53]:
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [54]:
ar_2 = [i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

- Пример объявления массивов (Часть 4)

### Примеры операций над массивами.

In [61]:
print(ones(5))
println(ones(2,3))
println(zeros(4))
println(fill(3.5,(3,2)))
println(repeat([1,2],3,3))
println(repeat([1 2],3,3))
a= collect(1:12)
println(a)
b= reshape(a,(2,6))
println(b)
println(b')
c= transpose(b)
println(c)
ar = rand(10:20, 10, 5)
println(ar)
println(ar[:, 2])
println(ar[:, [2, 5]])
println(ar[:, 2:4])
println(ar[[2, 4, 6], [1, 5]])
println(ar[1, 3:end])
println(sort(ar, dims=1))
println(sort(ar, dims=2))
println(ar .> 14)
println(findall(ar .> 14))

[1.0, 1.0, 1.0, 1.0, 1.0][1.0 1.0 1.0; 1.0 1.0 1.0]
[0.0, 0.0, 0.0, 0.0]
[3.5 3.5; 3.5 3.5; 3.5 3.5]
[1 1 1; 2 2 2; 1 1 1; 2 2 2; 1 1 1; 2 2 2]
[1 2 1 2 1 2; 1 2 1 2 1 2; 1 2 1 2 1 2]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[1 3 5 7 9 11; 2 4 6 8 10 12]
[1 2; 3 4; 5 6; 7 8; 9 10; 11 12]
[1 2; 3 4; 5 6; 7 8; 9 10; 11 12]
[18 14 16 20 18; 12 16 20 19 16; 19 19 14 11 12; 17 14 18 18 19; 17 14 17 18 12; 20 14 13 14 17; 13 10 14 11 19; 14 12 14 14 18; 11 18 19 20 20; 19 14 17 19 18]
[14, 16, 19, 14, 14, 14, 10, 12, 18, 14]
[14 18; 16 16; 19 12; 14 19; 14 12; 14 17; 10 19; 12 18; 18 20; 14 18]
[14 16 20; 16 20 19; 19 14 11; 14 18 18; 14 17 18; 14 13 14; 10 14 11; 12 14 14; 18 19 20; 14 17 19]
[12 16; 17 19; 20 17]
[16, 20, 18]
[11 10 13 11 12; 12 12 14 11 12; 13 14 14 14 16; 14 14 14 14 17; 17 14 16 18 18; 17 14 17 18 18; 18 14 17 19 18; 19 16 18 19 19; 19 18 19 20 19; 20 19 20 20 20]
[14 16 18 18 20; 12 16 16 19 20; 11 12 14 19 19; 14 17 18 18 19; 12 14 17 17 18; 13 14 14 17 20; 10 11 13 14

## **Задания для самостоятельного выполнения**

**1- Даны множества: 𝐴 = {0, 3, 4, 9}, 𝐵 = {1, 3, 4, 7}, 𝐶 = {0, 1, 2, 4, 7, 8, 9}. Найти 𝑃 = 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐵 ∪ 𝐴 ∩ 𝐶 ∪ 𝐵 ∩ 𝐶.**


In [62]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])

P = union(union(union(intersect(A, B), intersect(A, B)), intersect(A, C)), intersect(B, C))
print(P)

Set([0, 4, 7, 9, 3, 1])

- Решение 1.

**2- Приведите свои примеры с выполнением операций над множествами элементов разных типов.**

In [63]:
A = Set([1, 2, 3, 4])
B = Set(["meric", "doruk", "kymkc"])
C = union(A, B)

Set{Any} with 7 elements:
  4
  "meric"
  2
  "kymkc"
  3
  1
  "doruk"

In [64]:
D = intersect(A, B)

Set{Any}()

In [65]:
E = setdiff(B, A)

Set{String} with 3 elements:
  "meric"
  "kymkc"
  "doruk"

In [66]:
F = setdiff(A, B)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [67]:
issubset(A, B)

false

In [68]:
push!(A, 12)

Set{Int64} with 5 elements:
  4
  2
  12
  3
  1

In [69]:
pop!(A)

4

- Примеры операций над множествами разных типов 

**3- Создайте разными способами:**
   - массив (1, 2, 3, … 𝑁 − 1, 𝑁 ), 𝑁 выберите больше 20;


In [70]:
N = 30
A = collect(1:N)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]

- 3.2 массив (𝑁, 𝑁 − 1 … , 2, 1), 𝑁 выберите больше 20;

In [71]:
B = [i for i in N:-1:0]
print(B)

[30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

- 3.3 массив (1, 2, 3, … , 𝑁 − 1, 𝑁, 𝑁 − 1, … , 2, 1), 𝑁 выберите больше 20;

In [77]:
C = [i for i in 1:N]
for i in N-1:-1:1
    push!(C, i)
end
print(C)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

- 3.4 массив с именем tmp вида (4, 6, 3)

In [73]:
tmp = [4, 6, 3]
print(tmp)

[4, 6, 3]

- 3.5 массив, в котором первый элемент массива tmp повторяется 10 раз

In [74]:
for i in 1:1:9
    pushfirst!(tmp, tmp[1])
end
print(tmp)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3]

- 3.6 массив, в котором все элементы массива tmp повторяются 10 раз

In [75]:
tmp = [4, 6, 3]
tmp = repeat(tmp, 10)
print(tmp)

[4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3, 4, 6, 3]

- 3.7 массив, в котором первый элемент массива tmp встречается 11 раз, второй элемент — 10 раз, третий элемент — 10 раз

In [78]:
tmp = [4, 6, 3]
arr = [fill(tmp[1], 11); repeat(tmp[2:end], 10)]
print(arr)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3, 6, 3]

- 3.8 массив, в котором первый элемент массива tmp встречается 10 раз подряд, второй элемент — 20 раз подряд, третий элемент — 30 раз подряд

In [80]:
tmp = [4, 6, 3]
arr = [fill(tmp[1], 10); fill(tmp[2], 20); fill(tmp[3], 10)]
print(arr)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

- 3.9 массив из элементов вида  2𝑡𝑚𝑝[𝑖] , 𝑖 = 1, 2, 3, где элемент  2𝑡𝑚𝑝[3]  встречается 4 раза; посчитайте в полученном векторе, сколько раз встречается цифра 6, и выведите это значение на экран

In [81]:
tmp = [4, 6, 3]
tmp_sqr = [[2^tmp[i] for i in 1:length(tmp)]; fill(2^tmp[3], 3);]

println(tmp_sqr)

count = 0
numbers = []
for i in 1:1:length(tmp_sqr)
    while tmp_sqr[i] != 0
        r = tmp_sqr[i] % 10
        push!(numbers, r)
        tmp_sqr[i] = div(tmp_sqr[i], 10)
    end
end
for i in 1:1:length(numbers)
    if numbers[i] == 6
        count += 1
    end
end
print(count)

[16, 64, 8, 8, 8, 8]
2

- 3.10 вектор значений  𝑦=𝑒𝑥𝑐𝑜𝑠(𝑥)  в точках 𝑥 = 3, 3.1, 3.2, … , 6, найдите среднее значение 𝑦 

In [83]:
using Statistics
y = [exp(i)*cos(i) for i in 3:0.1:6]
mean(y)

53.11374594642971

- 3.11 вектор вида ( 𝑥𝑖,𝑦𝑗 ), 𝑥 = 0.1, 𝑖 = 3, 6, 9, … , 36, 𝑦 = 0.2, 𝑗 = 1, 4, 7, … , 34

In [88]:
x = 0.1 
y = 0.2
vector = []
j = 1
for i = 3:3:36
    if j != 37
        append!(vector, [(x^i, y^i)])
        j += 3
    end
end
print(vector)

Any[(0.0010000000000000002, 0.008000000000000002), (1.0000000000000004e-6, 6.400000000000002e-5), (1.0000000000000005e-9, 5.120000000000002e-7), (1.0000000000000008e-12, 4.096000000000003e-9), (1.0000000000000009e-15, 3.276800000000003e-11), (1.0000000000000008e-18, 2.621440000000002e-13), (1.0000000000000012e-21, 2.0971520000000026e-15), (1.0000000000000012e-24, 1.677721600000002e-17), (1.0000000000000015e-27, 1.342177280000002e-19), (1.0000000000000017e-30, 1.0737418240000018e-21), (1.0000000000000018e-33, 8.589934592000015e-24), (1.000000000000002e-36, 6.871947673600013e-26)]

- 3.12 вектор с элементами  2𝑖/𝑖 , 𝑖 = 1, 2, … , 𝑀, 𝑀 = 25

In [89]:
M = 25
vector_1 = [(2^i)/i for i=1:1:M]
print(vector_1)

[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]

 - 3.13 вектор вида (”fn1”, ”fn2”, …, ”fnN”), 𝑁 = 30

In [90]:
N = 30
vector_2 = [string("fn", i) for i=1:1:N]
print(vector_2)

["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]

- 3.14 векторы 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛) и 𝑦 = (𝑦1, 𝑦2, … , 𝑦𝑛) целочисленного типа длины 𝑛 = 250 как случайные выборки из совокупности 0, 1, … , 999; на его основе:

In [91]:
using StatsBase
n = 250
x = sample(0:999, n , replace=false)
y = sample(0:999, n , replace=false)

println(length(x))
println(x)
println(y)

250
[190, 498, 343, 528, 506, 572, 114, 901, 869, 76, 830, 585, 578, 639, 91, 630, 522, 514, 421, 16, 796, 896, 655, 353, 726, 182, 318, 697, 410, 387, 358, 482, 719, 601, 584, 445, 79, 350, 629, 370, 216, 851, 446, 219, 275, 749, 88, 862, 73, 357, 834, 821, 946, 172, 887, 858, 839, 222, 191, 278, 220, 433, 413, 126, 426, 575, 518, 977, 66, 931, 346, 606, 361, 866, 390, 838, 909, 282, 962, 586, 206, 949, 615, 335, 21, 85, 115, 208, 999, 89, 418, 146, 224, 845, 459, 986, 217, 4, 192, 161, 84, 588, 544, 173, 548, 95, 221, 725, 281, 246, 366, 293, 56, 571, 802, 793, 199, 447, 720, 256, 19, 3, 509, 800, 675, 619, 616, 461, 836, 755, 859, 922, 879, 8, 32, 815, 36, 34, 683, 449, 935, 850, 997, 623, 169, 376, 267, 51, 872, 844, 672, 388, 194, 23, 744, 491, 698, 467, 777, 722, 770, 0, 904, 727, 270, 7, 462, 326, 640, 593, 100, 443, 686, 160, 656, 556, 336, 972, 938, 636, 831, 632, 437, 987, 403, 77, 597, 132, 873, 26, 360, 363, 384, 327, 861, 241, 718, 112, 86, 651, 147, 645, 229, 812, 495, 27

- 3.14.1 – сформируйте вектор ( 𝑦2−𝑥1 , … ,  𝑦𝑛−𝑥𝑛−1)

In [92]:
j = 1
vector1 = Vector{Int}()
for i = 2:1:n+1
    if j != n
        append!(vector1, y[i] - x[j])
        j += 1
    end
end
print(vector1)

[249, 324, 514, -336, -147, -198, 236, -678, -629, 572, -689, 282, 320, -192, 622, -144, 274, 319, 53, 555, -456, -8, -348, -11, -128, 365, 44, -444, -169, -108, -148, -470, -448, -317, -518, -381, 652, -111, 60, -148, -73, -152, -357, 31, 406, -676, 128, -255, 841, -253, -220, -296, -446, -163, -651, -626, 149, -66, 290, 17, 352, -323, 12, 754, 5, 47, 383, -842, 181, -166, -1, 89, 356, -468, -34, -803, -363, -56, -404, -92, 113, 46, 312, 635, 296, 853, 369, 192, -341, 728, -201, 16, 706, -780, 101, -19, 446, 151, 332, 796, 337, -32, -353, 386, 315, 432, 572, -20, 679, -224, -347, -211, 138, 280, 94, -49, 291, 476, -227, 740, 278, 501, 442, -745, 124, 365, 124, 441, -349, -327, -48, -367, -258, 327, 210, 146, 420, 584, 29, -131, -798, 106, -430, -310, 103, -133, 389, 133, -136, -592, -427, 66, 783, 148, -406, 499, -303, 325, -743, 139, 145, 783, -744, -192, -102, 934, -109, 638, 178, -206, 623, 243, -50, 318, 302, 294, 576, -969, -377, -92, 111, -164, -370, -919, 232, 872, 215, 545, -3

- 3.14.2 – сформируйте вектор ( 𝑥1+2𝑥2−𝑥3 ,  𝑥2+2𝑥3−𝑥4 , … ,  𝑥𝑛−2+2𝑥𝑛−1−𝑥𝑛)

In [93]:
vector2 = Vector{Int}()
for i in 2:1:n-1
    append!(vector2, x[i-1] + 2*x[i] - x[i+1])
end
print(vector2)

[843, 656, 893, 968, 1536, -101, 1047, 2563, 191, 1151, 1422, 1102, 1765, 191, 829, 1160, 1129, 1340, -343, 712, 1933, 1853, 635, 1623, 772, 121, 1302, 1130, 826, 621, 603, 1319, 1337, 1324, 1395, 253, 150, 1238, 1153, -49, 1472, 1524, 609, 20, 1685, 63, 1739, 651, -47, 1204, 1530, 2541, 403, 1088, 1764, 2314, 1092, 326, 527, 285, 673, 1133, 239, 403, 1058, 634, 2406, 178, 1582, 1017, 1197, 462, 1703, 808, 1157, 2374, 511, 1620, 1928, 49, 1489, 1844, 1264, 292, 76, 107, -468, 2117, 759, 779, 486, -251, 1455, 777, 2214, 1416, 33, 227, 430, -259, 716, 1503, 342, 1174, 517, -188, 1390, 1041, 407, 685, 896, -166, 396, 1382, 2189, 744, 373, 1631, 1213, 291, -484, 221, 1434, 1531, 1297, 1390, 702, 1378, 1487, 1551, 1824, 2672, 863, -743, 1626, 853, -579, 951, 646, 1469, 1638, 2221, 2074, 585, 654, 859, -503, 951, 1888, 1800, 1254, 753, -504, 1020, 1028, 1420, 855, 1299, 1451, 2262, -134, 1081, 2088, 1260, -178, 605, 474, 1013, 1726, 350, 300, 1655, 350, 916, 1432, 256, 1342, 2212, 1379, 1666

- 3.14.3 – сформируйте вектор (sin(y1)/cos(x2),sin(y2)/cos(x3),....,sin(y(n-1))/cos(xn))

In [94]:
vector3 = Vector{Float32}()
j = 1
for i = 2:1:n+1
    if j != n
        append!(vector3, sin(y[j])/cos(x[i]))
        j += 1
    end
end
print(vector3)

Float32[-17.37312, 0.8688516, -0.9104341, -0.6218381, -0.36454967, 1.2216256, 0.18649112, 2.7993836, 0.06435942, 1.1612723, 0.93848234, 0.36368296, 0.257273, 0.4781639, -7.057537, 0.16035518, 2.3694336, -0.923808, 0.4802929, -0.96802586, 0.87174404, 29.470522, 2.1088812, 0.8022155, 0.42979577, -1.162829, 0.3911597, 29.652592, -1.1925386, 0.79289323, -2.4365485, -0.5133248, 0.9300116, 0.77670306, 2.1224341, 0.029633945, -3.2437167, 1.0772223, 0.311555, 1.1653287, -0.9326066, -1.0039972, 1.6324455, 7.78927, -3.6405973, 0.6640049, -1.8852216, -0.94548404, -1.4970552, -2.1793535, 0.6400545, 1.0594126, 0.49135745, -0.9758269, -0.43795526, 0.37858975, 0.92923456, -1.2435073, -28.495312, -0.33131632, -0.3552988, -1.9144822, -0.04686803, -2.5041459, -0.34806958, 0.6055469, 0.035360098, -0.5950699, 0.19055294, 1.0172199, 1.0558318, 0.5665569, -1.3786858, 0.7270633, -1.2003331, 1.784428, -0.5816015, -0.76055187, 2.0837104, -4.1707892, -0.7164705, -1.3581964, -1.8961413, 0.4165202, -0.69403887, -

- 3.14.4 вычислите summ(n-1 | i = 1)[(e^(-x)i+1)/xi+10]

In [95]:
sum_vector = 0
for i in 1:1:n-1
    sum_vector += exp(-x[i+1])/(x[i]+10)
end
print(sum_vector)

0.0030831681880273487

- 3.14.5 – выберите элементы вектора 𝑦, значения которых больше 600, и выведите на экран; определите индексы этих элементов

In [96]:
idx_y = findall(y .> 600)
print(y[idx_y])

[822, 857, 648, 867, 898, 713, 796, 833, 888, 731, 689, 699, 681, 607, 914, 614, 988, 880, 622, 901, 765, 695, 717, 995, 927, 970, 938, 658, 817, 930, 967, 663, 957, 863, 793, 705, 960, 851, 896, 744, 923, 996, 951, 799, 984, 740, 902, 811, 621, 961, 618, 712, 956, 656, 736, 977, 990, 792, 861, 915, 783, 941, 964, 818, 723, 686, 636, 958, 850, 912, 942, 635, 949, 812, 677, 688, 897, 756, 834, 668, 745, 718, 916, 879, 616, 716, 854, 615, 747, 903, 721, 824, 624, 841, 644, 751, 858, 974, 708, 738, 775]

- 3.14.6 – определите значения вектора 𝑥, соответствующие значениям вектора 𝑦, значения которых больше 600 (под соответствием понимается расположение на аналогичных индексных позициях)

In [98]:
inc_y = findall(y .> 600)
print(x[inc_y])

[343, 528, 830, 578, 639, 630, 514, 421, 655, 350, 370, 446, 749, 73, 357, 821, 222, 426, 518, 977, 346, 361, 866, 615, 335, 21, 115, 89, 418, 845, 217, 4, 84, 95, 725, 281, 246, 802, 793, 199, 720, 19, 800, 619, 616, 461, 836, 922, 8, 36, 683, 449, 997, 51, 844, 23, 698, 777, 770, 0, 904, 462, 640, 593, 443, 686, 160, 556, 336, 972, 632, 77, 597, 132, 873, 861, 241, 651, 147, 645, 138, 466, 598, 48, 565, 617, 673, 435, 540, 50, 200, 907, 976, 411, 767, 819, 306, 488, 312, 974, 211]

- 3.14.7 - сформируйте вектор (|𝑥1 − 𝑥| 1 2 , |𝑥2 − 𝑥| 1 2 , … , |𝑥𝑛 − 𝑥| 1 2 ), где 𝑥 обозначает среднее значение вектора 𝑥 = (𝑥1, 𝑥2, … , 𝑥𝑛);

In [100]:
vector4 = Vector{Float64}()
for i in 1:1:n
    append!(vector4, (abs(x[i] - mean(x)))^(0.5))
end
print(vector4)

[16.964079697997175, 4.496665431183426, 11.60947888580706, 7.086607086610631, 5.312249994117373, 9.706698717895803, 19.073017590302797, 20.57231148898927, 19.779282090106303, 20.044450603595998, 18.767525143182837, 10.3547090736534, 10.010993956645866, 12.697243795406939, 19.666723163760658, 12.33774695801466, 6.6498120274185215, 6.0183054093324335, 7.5352504935138, 21.48906698765677, 17.838721927313067, 20.450427868384565, 13.312400234367956, 11.170496855556603, 15.75499920660106, 17.198255725508908, 12.640411385710513, 14.806079832285116, 8.232860985101107, 9.527853903162033, 10.94440496326776, 2.0542638584174204, 15.531258802814408, 11.10045044131093, 10.30630874755846, 5.725382083319852, 19.969476708216465, 11.30398159941885, 12.297154142320899, 10.381714694596456, 16.179616806340007, 19.318902660347973, 5.637375275782159, 16.086640419926095, 14.240084269413575, 16.468758301705687, 19.7428468058687, 19.601530552484927, 20.119145111062746, 10.98999545040852, 18.873791352030995, 18.5

- 3.14.7 – определите, сколько элементов вектора 𝑦 отстоят от максимального значения не более, чем на 200

In [101]:
count_numbers = 0
max = maximum(y)
for i in 1:1:n
    if abs(y[i] - max) < 200
        count_numbers += 1
    end
end
print(count_numbers)

54

- 3.14.8 – определите, сколько чётных и нечётных элементов вектора 𝑥

In [105]:
even = 0
odd = 0
for i in 1:1:n
    if mod(x[i],2) == 0
        even += 1
    else
        odd += 1
    end
end
println("Even : ", even)
print("Odd : ", odd)

Even : 131
Odd : 119

- 3.14.9 – определите, сколько элементов вектора 𝑥 кратны 7

In [103]:
count7 = 0
for i in 1:1:n
    if mod(x[i], 7) == 0
        count7 += 1
    end
end
print("Sevens : ", count7)

Sevens : 42

- 3.14.10 – отсортируйте элементы вектора 𝑥 в порядке возрастания элементов вектора 𝑦

In [104]:
x_new = x[sortperm(y)]
print(x_new)

[229, 938, 887, 719, 293, 768, 395, 366, 722, 909, 675, 79, 459, 445, 987, 403, 732, 226, 88, 56, 215, 219, 389, 753, 834, 260, 413, 535, 274, 66, 850, 585, 384, 851, 192, 191, 727, 224, 743, 7, 744, 327, 718, 872, 173, 506, 571, 349, 482, 862, 146, 216, 869, 962, 812, 839, 858, 629, 76, 387, 815, 267, 388, 931, 275, 672, 410, 441, 601, 376, 15, 190, 358, 227, 584, 220, 3, 363, 353, 169, 85, 935, 949, 32, 491, 896, 726, 606, 901, 326, 838, 572, 697, 374, 114, 130, 218, 495, 100, 486, 467, 390, 999, 588, 126, 859, 575, 360, 498, 91, 194, 34, 437, 86, 16, 656, 278, 208, 522, 755, 560, 447, 256, 206, 685, 172, 917, 509, 26, 161, 946, 221, 270, 831, 112, 282, 318, 879, 544, 586, 548, 986, 636, 623, 796, 433, 546, 171, 182, 73, 821, 435, 565, 683, 8, 518, 976, 77, 160, 767, 830, 51, 89, 4, 645, 873, 749, 686, 861, 370, 361, 446, 281, 312, 449, 630, 617, 866, 466, 200, 443, 350, 844, 974, 461, 199, 138, 540, 819, 651, 346, 211, 904, 777, 725, 514, 619, 922, 132, 418, 593, 343, 907, 421, 147,

- 3.14.11 – выведите элементы вектора 𝑥, которые входят в десятку наибольших (top-10)

In [106]:
x_sort = sort(x, rev=true)
print(x_sort[1:10])

[999, 997, 987, 986, 977, 976, 974, 972, 962, 949]

- 3.14.12 – сформируйте вектор, содержащий только уникальные (неповторяющиеся) элементы вектора 𝑥.

In [107]:
x_uni = unique(x)
print(x_uni)
length(x_uni)

[190, 498, 343, 528, 506, 572, 114, 901, 869, 76, 830, 585, 578, 639, 91, 630, 522, 514, 421, 16, 796, 896, 655, 353, 726, 182, 318, 697, 410, 387, 358, 482, 719, 601, 584, 445, 79, 350, 629, 370, 216, 851, 446, 219, 275, 749, 88, 862, 73, 357, 834, 821, 946, 172, 887, 858, 839, 222, 191, 278, 220, 433, 413, 126, 426, 575, 518, 977, 66, 931, 346, 606, 361, 866, 390, 838, 909, 282, 962, 586, 206, 949, 615, 335, 21, 85, 115, 208, 999, 89, 418, 146, 224, 845, 459, 986, 217, 4, 192, 161, 84, 588, 544, 173, 548, 95, 221, 725, 281, 246, 366, 293, 56, 571, 802, 793, 199, 447, 720, 256, 19, 3, 509, 800, 675, 619, 616, 461, 836, 755, 859, 922, 879, 8, 32, 815, 36, 34, 683, 449, 935, 850, 997, 623, 169, 376, 267, 51, 872, 844, 672, 388, 194, 23, 744, 491, 698, 467, 777, 722, 770, 0, 904, 727, 270, 7, 462, 326, 640, 593, 100, 443, 686, 160, 656, 556, 336, 972, 938, 636, 831, 632, 437, 987, 403, 77, 597, 132, 873, 26, 360, 363, 384, 327, 861, 241, 718, 112, 86, 651, 147, 645, 229, 812, 495, 274, 1

250

**4- Создайте массив squares, в котором будут храниться квадраты всех целых чисел от 1 до 100**

In [110]:
sqr = [i^2 for i=1:1:100]
print(sqr)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

**5- Подключите пакет Primes (функции для вычисления простых чисел). Сгенерируйте массив myprimes, в котором будут храниться первые 168 простых чисел. Определите 89-е наименьшее простое число. Получите срез массива с 89-го до 99-го элемента включительно, содержащий наименьшие простые числа.
Я подключила пакет Primes для генерирования простых чисел.** 

In [111]:
using Primes
n = 1000
myprimes = primes(n)
print(myprimes)

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]

In [112]:
println(myprimes[89])
print(myprimes[89:99])

461
[461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523]

**6- Вычислите следующие выражения**
<br>
 - 1- 

In [113]:
sum((i^3)+4*(i^2) for i=10:1:100)

26852735

- 2-

In [115]:
M = 25
sum(((2^i)/i) + ((3^i)/(i^2)) for i=1:1:M)

2.1291704368143802e9

- 3-

In [117]:
summ = 1
temp = 1
for i in 3:2:39
    temp *= (i-1)/i
    summ += temp
end
print(summ)

6.976346137897618

#### **Выводы**
- Изучил структуры данных, реализованных в Julia. Научил применять их и операции над ними для решения задач.
