# Лабораторная работа № 1. Julia. Установка и настройка. Основные принципы.

In [2]:
;whoami

desktop-9ulgep1\meric


In [2]:
using Dates
datetimenow = Dates.now()

2023-11-10T23:03:01.130

In [3]:
2+3

5

In [4]:
print("hello world")

hello world

In [5]:
?println

search: println printstyled print sprint isprint



```
println([io::IO], xs...)
```

Print (using [`print`](@ref)) `xs` to `io` followed by a newline. If `io` is not supplied, prints to the default output stream [`stdout`](@ref).

See also [`printstyled`](@ref) to add colors etc.

# Examples

```jldoctest
julia> println("Hello, world")
Hello, world

julia> io = IOBuffer();

julia> println(io, "Hello", ',', " world.")

julia> String(take!(io))
"Hello, world.\n"
```


## part 2 ---------------------------------------------

## 

In [7]:
typeof(3), typeof(3.5), typeof(3/3.55), typeof(sqrt(3+4im)), typeof(pi)

(Int64, Float64, Float64, ComplexF64, Irrational{:π})

In [8]:
1.0/0.0, 1.0/(-0.0), 0.0/0.0

(Inf, -Inf, NaN)

In [9]:
typeof(1.0/0.0), typeof(1.0/-0.0), typeof(0.0/0.0)

(Float64, Float64, Float64)

In [10]:
for T in [Int8, Int16, Int32, Int64, Int128, UInt16, UInt32, UInt64, UInt128]
    println("$(lpad(T, 7)): [$(typemin(T)), $(typemax(T))]")
end

   Int8: [-128, 127]
  Int16: [-32768, 32767]
  Int32: [-2147483648, 2147483647]
  Int64: [-9223372036854775808, 9223372036854775807]
 Int128: [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]
 UInt16: [0, 65535]
 UInt32: [0, 4294967295]
 UInt64: [0, 18446744073709551615]
UInt128: [0, 340282366920938463463374607431768211455]


In [11]:
Int64(2.0), Char(2), typeof(Char(2))

(2, '\x02', Char)

In [12]:
convert(Int64, 2.0), convert(Char, 2)

(2, '\x02')

In [14]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

## part 3 ---------------------------------------------

In [17]:
function f(x)
    x^2
end

f (generic function with 1 method)

In [18]:
f(4)

16

In [19]:
g(x) = x^2

g (generic function with 1 method)

In [20]:
g(8)

64

In [21]:
a = [4 7 6]
b = [1, 2, 3]
a[2], b[2]

(7, 2)

In [23]:
a = 1; b = 2; c = 3; d = 4
Am = [a b; c d]

2×2 Matrix{Int64}:
 1  2
 3  4

In [24]:
Am[1, 1], Am[1, 2], Am[2, 1], Am[2, 2]

(1, 2, 3, 4)

In [26]:
aa = [1 2]
AA = [1 2; 3 4]
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [27]:
aa, AA, aa'

([1 2], [1 2; 3 4], [1; 2;;])

# Задания для самостоятельной работы

1. Изучите документацию по основным функциям Julia для чтения / записи / выво-
да информации на экран: read(), readline(), readlines(), readdlm(), print(),
println(), show(), write(). Приведите свои примеры их использования, поясняя
особенности их применения.

In [29]:
?read()

```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [30]:
str_hello = IOBuffer("hello world!");

In [31]:
read(str_hello, String)

"hello world!"

In [32]:
open("lab01_file1.txt", "w") do io
    write(io, "hello world\n");
end

12

In [36]:
readline("lab01_file1.txt"), readline("lab01_file1.txt", keep=true)

("hello world", "hello world\n")

In [37]:
open("lab01_file2.txt", "w") do io
    write(io, "ashdsha ajsjdjsad ahshah ajsjdahsd\nashdashdhasdh ahsdhasdhsahadhash\n ahsdhadhsaahsdhasdh ashdashdhas\n");
end

101

In [38]:
readlines("lab01_file2.txt")

3-element Vector{String}:
 "ashdsha ajsjdjsad ahshah ajsjdahsd"
 "ashdashdhasdh ahsdhasdhsahadhash"
 " ahsdhadhsaahsdhasdh ashdashdhas"

In [39]:
readlines("lab01_file2.txt", keep=true)

3-element Vector{String}:
 "ashdsha ajsjdjsad ahshah ajsjdahsd\n"
 "ashdashdhasdh ahsdhasdhsahadhash\n"
 " ahsdhadhsaahsdhasdh ashdashdhas\n"

In [43]:
using DelimitedFiles
number_x = [1; 2; 3; 4; 5];
number_y = [6; 7; 8; 9; 10];
open("lab01_file3.txt", "w") do io
    writedlm(io, [number_x number_y])
end;
readdlm("lab01_file3.txt", Int32), readdlm("lab01_file3.txt", Float32)

(Int32[1 6; 2 7; … ; 4 9; 5 10], Float32[1.0 6.0; 2.0 7.0; … ; 4.0 9.0; 5.0 10.0])

In [44]:
print("asjdasjdjs asjdjasdjasj asjsdjasdjsajd.")
print("asjdsajdjas akkwidjajaowodwaokakaskdw.")

asjdasjdjs asjdjasdjasj asjsdjasdjsajd.asjdsajdjas akkwidjajaowodwaokakaskdw.

In [45]:
println("hi there general kenobi!")
print("hey there")
print("idk at this point")

hi there general kenobi!
hey thereidk at this point

In [46]:
show("LAB01: asjdjsadja, ajsajda")

"LAB01: asjdjsadja, ajsajda"

In [47]:
io = IOBuffer();
write(io, "sajdasjdsja, sjdsadjsajdas. jasdjsajdjwdiwidwakdsdjw.skdaskdksakdwkadisidjafwd adjdjwadiaisdjajd kw")

99

2. Изучите документацию по функции parse(). Приведите свои примеры её использо-
вания, поясняя особенности её применения.

In [50]:
println(parse(Int, "74334332327"))
print(parse(Complex{Float64}, "62.45e-1 + 10.98im"))

74334332327
6.245 + 10.98im

3. Изучите синтаксис Julia для базовых математических операций с разным типом пере-
менных: сложение, вычитание, умножение, деление, возведение в степень, извлечение
корня, сравнение, логические операции. Приведите свои примеры с пояснениями по
особенностям их применения.

In [55]:
x = 5; y = 14
println("addition: ", (x + y))
println("substration", (x - y))
println("division", (x / y))
println("multiuplication", (x * y))
println("x to the power of y", (x^y))
println("square root", sqrt(x^2+y^2))
println("unary plus", +x)
println("unary minus", -x)
println("logical operations:")
println(x == y)
println(x !== y)
println(x < y)
println(x > y)
println("bitewise operations:")
println(~x)
println(x & y)
println(x | y)
println("bit slide to right ", x >> y)
println("bit slide to left ", x << y)
println("Сдвиг вправо без учета знака", x >>> y)

addition: 19
substration-9
division0.35714285714285715
multiuplication70
x to the power of y6103515625
square root14.866068747318506
unary plus5
unary minus-5
logical operations:
false
true
true
false
bitewise operations:
-6
4
15
bit slide to right 0
bit slide to left 81920
Сдвиг вправо без учета знака0


4. Приведите несколько своих примеров с пояснениями с операциями над матрицами
и векторами: сложение, вычитание, скалярное произведение, транспонирование,
умножение на скаляр

In [57]:
L = [1 2 3;4 5 6;7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [58]:
R = [3 4 7;1 2 3;9 8 7]

3×3 Matrix{Int64}:
 3  4  7
 1  2  3
 9  8  7

In [59]:
L + R

3×3 Matrix{Int64}:
  4   6  10
  5   7   9
 16  16  16

In [60]:
R - L

3×3 Matrix{Int64}:
  2   2   4
 -3  -3  -3
  2   0  -2

In [61]:
R * L

3×3 Matrix{Int64}:
 68   82   96
 30   36   42
 90  114  138

In [62]:
R'

3×3 adjoint(::Matrix{Int64}) with eltype Int64:
 3  1  9
 4  2  8
 7  3  7

In [63]:
Q = 3

3

In [64]:
R * Q

3×3 Matrix{Int64}:
  9  12  21
  3   6   9
 27  24  21